version: "3"
services:
  flask:
    container_name: flask_chatbot
    build:
      context: ./chatbot
    ports:
      - 9000:5000
    volumes:
      - ./:/flask_chatbot
    environment:
      - FLASK_APP=chatbot
      - FLASK_ENV=development
    depends_on:
      - mysql
  
  #mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatbot
      MYSQL_USER: chatbot
      MYSQL_PASSWORD: chatbot
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306