"""empty message

Revision ID: 01abe9f19892
Revises: 57594afd54b6
Create Date: 2019-10-02 06:34:31.597304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01abe9f19892'
down_revision = '57594afd54b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('fitted_model_path', sa.Text(), nullable=False),
    sa.Column('faq_list_id', sa.Integer(), nullable=False),
    sa.Column('enable_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faq_list_id'], ['faq_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bots')
    # ### end Alembic commands ###
