"""empty message

Revision ID: 3629d0c90e24
Revises: 042f9fa4381c
Create Date: 2019-10-15 18:12:52.960707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3629d0c90e24'
down_revision = '042f9fa4381c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('fitted_faq_list_id', sa.Integer(), nullable=True))
    op.add_column('bots', sa.Column('last_fitted_at', sa.DateTime(), nullable=True))
    op.drop_constraint('bots_ibfk_1', 'bots', type_='foreignkey')
    op.create_foreign_key(None, 'bots', 'faq_lists', ['fitted_faq_list_id'], ['id'])
    op.drop_column('bots', 'faq_list_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('faq_list_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.create_foreign_key('bots_ibfk_1', 'bots', 'faq_lists', ['faq_list_id'], ['id'])
    op.drop_column('bots', 'last_fitted_at')
    op.drop_column('bots', 'fitted_faq_list_id')
    # ### end Alembic commands ###
