"""empty message

Revision ID: 403e67bdc113
Revises: 3e0acf52e984
Create Date: 2019-10-11 09:30:46.923350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403e67bdc113'
down_revision = '3e0acf52e984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('enable_flag', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'enable_flag')
    # ### end Alembic commands ###
