"""empty message

Revision ID: 4de944604bc1
Revises: cb306f68dd11
Create Date: 2019-10-10 10:39:42.217173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de944604bc1'
down_revision = 'cb306f68dd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs_faqs',
    sa.Column('from_faq_id', sa.Integer(), nullable=True),
    sa.Column('to_faq_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_faq_id'], ['faqs.id'], ),
    sa.ForeignKeyConstraint(['to_faq_id'], ['faqs.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faqs_faqs')
    # ### end Alembic commands ###
