"""empty message

Revision ID: 5318af3ba478
Revises: 2e6ff67b2c0e
Create Date: 2019-10-29 06:13:15.875618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5318af3ba478'
down_revision = '2e6ff67b2c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talk_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('talk_type', sa.String(length=255), nullable=True),
    sa.Column('request_static_answer_name', sa.Text(), nullable=True),
    sa.Column('request_query', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('response_faq_id', sa.Integer(), nullable=True),
    sa.Column('response_faqs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('faqs_faqs', 'faq_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('faqs_faqs', 'faq_list_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('faqs_faqs', 'question',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faqs_faqs', 'question',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('faqs_faqs', 'faq_list_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('faqs_faqs', 'faq_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_table('talk_logs')
    # ### end Alembic commands ###
