"""empty message

Revision ID: 56dd3ef8e39f
Revises: fd84199c2d2f
Create Date: 2019-10-20 23:48:09.508677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56dd3ef8e39f'
down_revision = 'fd84199c2d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_static_answer_settings', sa.Column('static_answer_name', sa.Text(), nullable=False))
    op.drop_constraint('site_static_answer_settings_ibfk_2', 'site_static_answer_settings', type_='foreignkey')
    op.drop_column('site_static_answer_settings', 'static_answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_static_answer_settings', sa.Column('static_answer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('site_static_answer_settings_ibfk_2', 'site_static_answer_settings', 'static_answers', ['static_answer_id'], ['id'])
    op.drop_column('site_static_answer_settings', 'static_answer_name')
    # ### end Alembic commands ###
