"""empty message

Revision ID: 668986a83b66
Revises: 996be83be195
Create Date: 2019-10-30 07:49:17.171990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '668986a83b66'
down_revision = '996be83be195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('fit_flag', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faqs', 'fit_flag')
    # ### end Alembic commands ###
