"""empty message

Revision ID: 996be83be195
Revises: 5318af3ba478
Create Date: 2019-10-29 10:48:53.780956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996be83be195'
down_revision = '5318af3ba478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talk_logs', sa.Column('score', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk_logs', 'score')
    # ### end Alembic commands ###
