"""empty message

Revision ID: b3992d394ca2
Revises: 403e67bdc113
Create Date: 2019-10-15 07:20:41.877971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3992d394ca2'
down_revision = '403e67bdc113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('static_answers_faqs',
    sa.Column('static_answer_id', sa.Integer(), nullable=False),
    sa.Column('faq_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faq_id'], ['faqs.id'], ),
    sa.ForeignKeyConstraint(['static_answer_id'], ['static_answers.id'], ),
    sa.PrimaryKeyConstraint('static_answer_id', 'faq_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_answers_faqs')
    op.drop_table('static_answers')
    # ### end Alembic commands ###
