"""empty message

Revision ID: bd3fbc93e1a7
Revises: 56dd3ef8e39f
Create Date: 2019-10-25 01:54:13.377344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd3fbc93e1a7'
down_revision = '56dd3ef8e39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs_faqs', sa.Column('faq_id', sa.Integer(), nullable=False))
    op.add_column('faqs_faqs', sa.Column('faq_list_id', sa.Integer(), nullable=False))
    op.add_column('faqs_faqs', sa.Column('question', sa.Text(), nullable=False))
    op.drop_constraint('faqs_faqs_ibfk_1', 'faqs_faqs', type_='foreignkey')
    op.drop_constraint('faqs_faqs_ibfk_2', 'faqs_faqs', type_='foreignkey')
    op.create_foreign_key(None, 'faqs_faqs', 'faq_lists', ['faq_list_id'], ['id'])
    op.create_foreign_key(None, 'faqs_faqs', 'faqs', ['faq_id'], ['id'])
    op.drop_column('faqs_faqs', 'to_faq_id')
    op.drop_column('faqs_faqs', 'from_faq_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs_faqs', sa.Column('from_faq_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('faqs_faqs', sa.Column('to_faq_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'faqs_faqs', type_='foreignkey')
    op.drop_constraint(None, 'faqs_faqs', type_='foreignkey')
    op.create_foreign_key('faqs_faqs_ibfk_2', 'faqs_faqs', 'faqs', ['to_faq_id'], ['id'])
    op.create_foreign_key('faqs_faqs_ibfk_1', 'faqs_faqs', 'faqs', ['from_faq_id'], ['id'])
    op.drop_column('faqs_faqs', 'question')
    op.drop_column('faqs_faqs', 'faq_list_id')
    op.drop_column('faqs_faqs', 'faq_id')
    # ### end Alembic commands ###
