"""empty message

Revision ID: cc098597cee2
Revises: bd3fbc93e1a7
Create Date: 2019-10-27 01:50:18.636466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc098597cee2'
down_revision = 'bd3fbc93e1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_lists', sa.Column('not_found_faq_id', sa.Integer(), nullable=True))
    op.add_column('faq_lists', sa.Column('start_faq_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'faq_lists', 'faqs', ['not_found_faq_id'], ['id'])
    op.create_foreign_key(None, 'faq_lists', 'faqs', ['start_faq_id'], ['id'])
    op.add_column('static_answers_faqs', sa.Column('question', sa.Text(), nullable=False))
    op.drop_constraint('static_answers_faqs_ibfk_1', 'static_answers_faqs', type_='foreignkey')
    op.drop_column('static_answers_faqs', 'faq_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('static_answers_faqs', sa.Column('faq_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('static_answers_faqs_ibfk_1', 'static_answers_faqs', 'faqs', ['faq_id'], ['id'])
    op.drop_column('static_answers_faqs', 'question')
    op.drop_constraint(None, 'faq_lists', type_='foreignkey')
    op.drop_constraint(None, 'faq_lists', type_='foreignkey')
    op.drop_column('faq_lists', 'start_faq_id')
    op.drop_column('faq_lists', 'not_found_faq_id')
    # ### end Alembic commands ###
