"""empty message

Revision ID: fd84199c2d2f
Revises: 5c36b0f5c833
Create Date: 2019-10-19 18:52:00.099458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd84199c2d2f'
down_revision = '5c36b0f5c833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('domain', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
